# NumPy について
NumPy は配列の作成、処理をするためのライブラリである。
NumPy の配列は、Python標準のリストと比較すると、格納できるデータ型が 1種類であることや固定長あるという制限がありますが、計算速度が速いです。
また、計算のために便利な機能をたくさん持っている。

In [5]:
import numpy as np

# 数値型の配列
int_arr = np.array([1, 2, 3, 4, 5])
print(type(int_arr))
print(int_arr)
print(int_arr.dtype)

# 文字列型の配列
str_arr = np.array(["いろはにほへと", "ちりぬるを", "わかよたれそ", "つねならむ"])
print(type(str_arr))
print(str_arr)
print(str_arr.dtype)


<class 'numpy.ndarray'>
[1 2 3 4 5]
int32
<class 'numpy.ndarray'>
['いろはにほへと' 'ちりぬるを' 'わかよたれぞ' 'つねならむ']
<U7


In [134]:
import numpy as np

# データ型を指定した配列の生成
int_array = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(type(int_array))
print(int_arr)
print(int_arr.dtype)

# 配列のデータ型の変更
int_arr = int_arr.astype(np.int64)
print(type(int_arr))
print(int_arr)
print(int_arr.dtype)

# 多次元配列の生成
a1 = np.array([
    [1, 2, 3], [2, 4, 6], [10, 20, 30]
])
print("shape(配列の構造の表示): " + str(a1.shape))
print(a1)

# 多次元配列の生成
a2 = np.zeros((2, 3), dtype=np.int8)
print("shape(配列の構造の表示): " + str(a2.shape))
print(a2)

# 1次元配列を多次元配列へ変換する
a3 = np.array([1, 2, 3, 4, 5, 6])
print(a3)

# 2x3の配列に変換する
a3 = a3.reshape(2,3)
print(a3)

#多次元配列を1次元配列へ変換する
# 多次元配列の生成
sourcedata = np.arange(1, 13).reshape(3, 4)
print(sourcedata)
# 3x4の配列を1次元の配列へ変換する。
# flatten() は元の配列が残る。ravelは元の配列が消滅する可能性がある。
array1 = sourcedata.flatten()
print(array1)

array2 = sourcedata.ravel()
print(array2)




<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
<class 'numpy.ndarray'>
[1 2 3 4 5]
int64
shape(配列の構造の表示): (3, 3)
[[ 1  2  3]
 [ 2  4  6]
 [10 20 30]]
shape(配列の構造の表示): (2, 3)
[[0 0 0]
 [0 0 0]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [111]:
""" numpy のメソッド
"""
import numpy as np

# arange
t1 = np.arange(10)
print(t1)

t2 = np.arange(0, 11, 2)
print(t2)

# linspace(start, stop, num):  start以上、stop以下の価を num分割する。
# 使い方が難しい
# 1, 5 とはならない。でも、これは理解できる。
t3 = np.linspace(1, 10, 2)
print("2分割: " + str(t3))

# 1, 5, 10 とはならない。確かに両端を 1 と 10 にすると、中間は 5.5。
t3 = np.linspace(1, 10, 3)
print(f"3分割 {t3}")


# 0 - 10 だと、中間が 5 になる。
t4 = np.linspace(0, 10, 3)
print(f"3分割 {str(t4)}")


# np.empty(n): n個の要素を持つ配列を生成する。
# 仮の配列を作成するのに使う。値が初期化されないことに気を付ける。
t5 = np.empty(10)
print(t5)

# np.zeros(n): n個の要素を持つ配列を生成する。0で初期化する。
t6 = np.zeros(10)
print(t6)

# np.ones(n): n個の要素を持つ配列を生成する。1で初期化する。
t7 = np.ones(10)
print(t7)

# np.random.rand(n): n個の要素を持つ配列を生成する。0以上1未満のランダムな数値で初期化する。
t8 = np.random.rand(10)
print(t8)

# ランダムな数値を整数にする場合
t8 = t8 * 5 + 1
t8 = t8.astype(np.int8)
print(f"1-5 のランダムな数値: {t8}")


# np.concatenate([array1, array2]): 既存の配列を連結します。
iroha1 = ["色は匂えど", "散りぬるを"]
iroha2 = ["我が世誰ぞ", "常ならん"]

iroha3 = np.concatenate([iroha1, iroha2])
print(iroha3)


# リストと ndarray の変換
list1 = [1, 2, 3]
print(f"listを生成: {type(list1)}")

array1 = np.array(list1)
print(f"listをndarrayに変換: {type(array1)}")

list2 = array1.tolist()
print(f"ndarrayをlistに変換: {type(list2)}")



[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
2分割: [ 1. 10.]
3分割 [ 1.   5.5 10. ]
3分割 [ 0.  5. 10.]
[0.85136213 0.16356767 0.50535207 0.3446498  0.71717113 0.96320032
 0.68299937 0.78051726 0.70913816 0.62273229]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.14328479 0.23368017 0.75684295 0.21640149 0.33637749 0.97923799
 0.80045206 0.38659167 0.18742256 0.71784925]
1-5 のランダムな数値: [1 2 4 2 2 5 5 2 1 4]
['色は匂えど' '散りぬるを' '我が世誰ぞ' '常ならん']
listを生成: <class 'list'>
listをndarrayに変換: <class 'numpy.ndarray'>
ndarrayをlistに変換: <class 'list'>


In [183]:
# 元データ(多次元配列)の生成
sourcedata = np.arange(1, 13).reshape(3, 4)

# スライスを使用した表示
print(sourcedata)
print(f"[0,0]: {sourcedata[0,0]}") 
print(f"[2,3]: {sourcedata[2,3]}")
print(sourcedata[1:3, 2:4])

# 要素の追加 (1次元配列の場合)
array1 = np.arange(1, 13)
array2 = np.append([100], array1)
print(f"array2: {array2}")

# 位置を指定しての要素の追加
array4 = np.insert(array2, 3, [200])
print(array4)

# 多次元配列に np.append() を使うと、一次元の配列に変換される。
array3 = np.append([10, 10, 10, 10], sourcedata)
print(f"array3: {array3}")

# 多次元配列に要素追加する場合には insert を使う
# nsert(処理対象の配列, 挿入位置, 挿入するデータ, 0|1)
# 0は縦に挿入、1は横に挿入
array5 = np.insert(sourcedata, 2, [11, 11, 11, 11], 0)
print(f"array5: {array5}")

# 多次元配列の末尾に値を追加する場合
a, b = sourcedata.shape
array6 = np.insert(sourcedata, a, [22, 22, 22, 22], 0)
print(f"array6: {array6}")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0,0]: 1
[2,3]: 12
[[ 7  8]
 [11 12]]
array2: [100   1   2   3   4   5   6   7   8   9  10  11  12]
[100   1   2 200   3   4   5   6   7   8   9  10  11  12]
array3: [10 10 10 10  1  2  3  4  5  6  7  8  9 10 11 12]
array5: [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 11 11 11]
 [ 9 10 11 12]]
array6: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [22 22 22 22]]


In [195]:
import numpy as np

# 元データ(多次元配列)の生成
data = np.arange(1, 13).reshape(3, 4)
print(f"元の配列: {data}")

# 要素の削除: 行を削除
# delete(対象データ, 削除対象, 0|1): 0 だと行を削除
array1 = np.delete(data, 1, 0)
print(f"2行目を削除: {array1}")

# 要素の削除: 行を削除
# delete(対象データ, 削除対象, 0|1): 1 だと列を削除
array1 = np.delete(data, 2, 1)
print(f"3列目を削除: {array1}")


元の配列: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2行目を削除: [[ 1  2  3  4]
 [ 9 10 11 12]]
3列目を削除: [[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [206]:
import numpy as np

# サンプルデータ生成
data = np.arange(1, 13)
print(data)

# 配列に対する計算: 各要素に対して 10を掛ける
print(data * 10)


# サンプルデータ生成
d1 = np.arange(1, 13).reshape(3, 4)
d2 = np.arange(1, 5).reshape(1, 4)
print(f"d1: {d1}")
print(f"d2: {d2}")
# d1 と d2 を各列ごとに計算する
print(f"d1*d2: {d1*d2}")


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 10  20  30  40  50  60  70  80  90 100 110 120]
d1: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
d2: [[1 2 3 4]]
d1*d2: [[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]


In [286]:
"""
ユニバーサル関数
"""
import numpy as np

# 計算対象のデータの生成: 1-5 の整数
data = np.random.rand(5) * 5 + 1
print(data)

# np.floor(): 切り捨て: 1-5 の値をとる。
data1 = np.array(np.floor(data), dtype=np.int16)
print(f"切り捨て: {data1}")

# np.ceil(): 切り上げ: 1-6 の値をとる。
data2 = np.array(np.ceil(data), dtype=np.int16)
print(f"切り上げ: {data2}")

# np.round(): 四捨五入: 1-6 の値をとる。
data3 = np.array(np.round(data), dtype=np.int16)
print(f"四捨五入: {data3}")


[4.37705976 1.65707558 1.73966615 3.4795927  3.57352202]
切り捨て: [4 1 1 3 3]
切り上げ: [5 2 2 4 4]
四捨五入: [4 2 2 3 4]


In [296]:
import numpy as np

# 元データ
d = np.arange(1, 10).reshape(3, 3)
print(d)

# 左右を反転する
d1 = np.fliplr(d)
print(f"fliplr: 左右反転:\n{d1}")

# 上下を反転する
d1 = np.flipud(d)
print(f"fliplr: 上下反転:\n{d1}")

# 反時計回りに90度回転する
# 第2引数: 1:90度, 2:180度, 3:270度
d1 = np.rot90(d, 1)
print(f"rot90(d, 1): 反時計回り 90度回転:\n{d1}")



[[1 2 3]
 [4 5 6]
 [7 8 9]]
fliplr: 左右反転:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
fliplr: 上下反転:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
rot90(d, 1): 反時計回り 90度回転:
[[3 6 9]
 [2 5 8]
 [1 4 7]]
